# Generated by Django 5.2.6 on 2025-09-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
