# Generated by Django 5.2.6 on 2025-09-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
