# Generated by Django 5.2.6 on 2025-09-29 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacto', '0006_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telemovel', models.CharField(max_length=15, verbose_name='Telemóvel')),
                ('assunto', models.CharField(choices=[('', 'Selecione o assunto'), ('suporte', 'Suporte Técnico'), ('vendas', 'Informação de Vendas'), ('parceria', 'Proposta de Parceria'), ('reclamacao', 'Reclamação'), ('outro', 'Outro')], max_length=20, verbose_name='Assunto')),
                ('mensagem', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('lido', models.BooleanField(default=False, verbose_name='Mensagem Lida')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-data_envio'],
            },
        ),
    ]
