# Generated by Django 4.2.25 on 2025-10-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='respondido',
            field=models.BooleanField(default=False, verbose_name='Respondido'),
        ),
    ]
