# Generated by Django 4.2.7 on 2025-10-10 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('telemovel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telemóvel')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('provincia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Província')),
                ('municipio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Município')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Foto de Perfil')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro da equipe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'conta_usuario',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
