# Generated by Django 4.2.7 on 2025-10-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_usuario_first_name_usuario_last_name'),
    ]

    operations = [
    ]
