# Generated by Django 5.2.6 on 2025-09-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_usuario_options_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
