# Generated by Django 5.2.6 on 2025-09-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='Superusuário'),
        ),
    ]
