# Generated by Django 4.2.25 on 2025-10-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
    ]
