# Generated by Django 5.2.6 on 2025-09-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Equipe'),
        ),
    ]
