# Generated by Django 5.2.6 on 2025-09-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superusuário'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Província'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telemovel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telemóvel'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
