# Generated by Django 5.2.6 on 2025-10-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0008_alter_usuario_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Foto de Perfil'),
        ),
    ]
