# Generated by Django 4.2.7 on 2025-10-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0012_alter_usuario_foto_perfil_alter_usuario_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True, verbose_name='Nome de usuário'),
        ),
    ]
