# Generated by Django 5.2.6 on 2025-10-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Vídeo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo_video', models.FileField(help_text='Formatos suportados: MP4, WebM, OGG', upload_to='videos_historia/', verbose_name='Arquivo de Vídeo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagem de capa para o vídeo', null=True, upload_to='thumbnails_videos/', verbose_name='Thumbnail')),
                ('url_youtube', models.URLField(blank=True, help_text='Link alternativo do YouTube', verbose_name='URL do YouTube')),
                ('ativo', models.BooleanField(default=True, verbose_name='Vídeo Ativo')),
                ('ordem_exibicao', models.IntegerField(default=0, help_text='Número para ordenar os vídeos (menor aparece primeiro)', verbose_name='Ordem de Exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vídeo da História',
                'verbose_name_plural': 'Vídeos da História',
                'ordering': ['ordem_exibicao', 'data_criacao'],
            },
        ),
    ]
