# Generated by Django 5.2.6 on 2025-10-05 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videohistoria',
            name='formato_video',
            field=models.CharField(choices=[('mp4', 'MP4'), ('webm', 'WebM'), ('ogg', 'OGG'), ('youtube', 'YouTube')], default='mp4', max_length=10, verbose_name='Formato do Vídeo'),
        ),
        migrations.AlterField(
            model_name='videohistoria',
            name='arquivo_video',
            field=models.FileField(help_text='Formatos suportados: MP4 (H.264), WebM, OGG. Tamanho máximo: 100MB', upload_to='videos_historia/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Arquivo de Vídeo'),
        ),
        migrations.AlterField(
            model_name='videohistoria',
            name='ordem_exibicao',
            field=models.IntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='videohistoria',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagem de capa para o vídeo (16:9 recomendado)', null=True, upload_to='thumbnails_videos/', verbose_name='Thumbnail'),
        ),
    ]
