# Generated by Django 5.2.6 on 2025-10-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre', '0002_videohistoria_formato_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videohistoria',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='Vídeo Principal'),
        ),
    ]
