# Generated by Django 4.2.25 on 2025-10-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('tipo_periodo', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10)),
                ('total_pedidos_entregues', models.IntegerField(default=0)),
                ('total_pedidos_cancelados', models.IntegerField(default=0)),
                ('valor_total_entregues', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pedidos_dia', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balanço',
                'verbose_name_plural': 'Balanços',
                'ordering': ['-data_referencia', '-tipo_periodo'],
                'unique_together': {('data_referencia', 'tipo_periodo')},
            },
        ),
    ]
