# Generated by Django 4.2.25 on 2025-10-25 12:12

import balanco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioBalanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_relatorio', models.CharField(default='Relatório Personalizado', max_length=100, verbose_name='Nome do Relatório')),
                ('data_inicio', models.DateField(default=balanco.models.data_hoje, verbose_name='Data de Início')),
                ('data_fim', models.DateField(default=balanco.models.data_hoje, verbose_name='Data de Término')),
                ('total_pedidos_entregues', models.IntegerField(default=0, verbose_name='Pedidos Entregues')),
                ('total_pedidos_cancelados', models.IntegerField(default=0, verbose_name='Pedidos Cancelados')),
                ('valor_total_entregues', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total Entregue')),
                ('total_pedidos_periodo', models.IntegerField(default=0, verbose_name='Total de Pedidos no Período')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relatório de Balanço',
                'verbose_name_plural': 'Relatórios de Balanço',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='Balanco',
        ),
    ]
