# Generated by Django 4.2.25 on 2025-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco', '0002_relatoriobalanco_delete_balanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriobalanco',
            name='total_vendido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Vendido (Realizado - Cancelado)'),
        ),
    ]
