# Generated by Django 4.2.25 on 2025-10-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco', '0003_relatoriobalanco_total_vendido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriobalanco',
            name='total_vendido',
        ),
        migrations.RemoveField(
            model_name='relatoriobalanco',
            name='valor_total_entregues',
        ),
        migrations.AddField(
            model_name='relatoriobalanco',
            name='subtotal_pedidos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal (Todos os Pedidos)'),
        ),
        migrations.AddField(
            model_name='relatoriobalanco',
            name='total_geral',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Geral (Subtotal - Cancelados)'),
        ),
        migrations.AddField(
            model_name='relatoriobalanco',
            name='valor_total_cancelados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total Cancelado'),
        ),
    ]
