# Generated by Django 5.2.6 on 2025-10-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'ordering': ['-data_adicao'], 'verbose_name': 'Item do Carrinho', 'verbose_name_plural': 'Itens do Carrinho'},
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together=set(),
        ),
    ]
