# Generated by Django 4.2.25 on 2025-10-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinho', '0002_alter_itemcarrinho_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoentrega',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número do Pedido'),
        ),
    ]
