# Generated by Django 4.2.25 on 2025-10-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinho', '0003_pedidoentrega_numero_pedido'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carrinho',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'aberto')), fields=('usuario', 'estado'), name='unique_open_cart_per_user'),
        ),
    ]
