# Generated by Django 4.2.25 on 2025-10-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carinho', '0004_carrinho_unique_open_cart_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carrinho',
            name='unique_open_cart_per_user',
        ),
    ]
