# Generated by Django 4.2.25 on 2025-10-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinho', '0005_remove_carrinho_unique_open_cart_per_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carrinho',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'aberto')), fields=('usuario', 'estado'), name='carrinho_aberto_unico_por_usuario'),
        ),
    ]
