# Generated by Django 4.2.25 on 2025-10-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_favorito_options'),
        ('carinho', '0006_carrinho_carrinho_aberto_unico_por_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'produto')},
        ),
    ]
