# Generated by Django 5.2.6 on 2025-09-30 10:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('descricao_curta', models.CharField(blank=True, max_length=300, verbose_name='Descrição Curta')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço')),
                ('categoria', models.CharField(choices=[('eletronicos', 'Eletrónicos'), ('informatica', 'Informática'), ('livros', 'Livros'), ('casa', 'Casa e Decoração'), ('moda', 'Moda'), ('esportes', 'Esportes'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('esgotado', 'Esgotado')], default='ativo', max_length=10, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
