# Generated by Django 5.2.6 on 2025-09-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Formatos suportados: JPG, PNG, GIF', null=True, upload_to='produtos/', verbose_name='Imagem'),
        ),
    ]
