# Generated by Django 5.2.6 on 2025-10-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição dos produtos (menor número aparece primeiro)', verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Hambúrgueres', 'Hambúrgueres'), ('Lanches', 'Lanches'), ('Bebidas', 'Bebidas')], max_length=20, verbose_name='Categoria'),
        ),
    ]
