# Generated by Django 4.2.7 on 2025-10-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_produto_ordem_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('hamburguer', 'hamburguer'), ('Lanches', 'Lanches'), ('Bebidas', 'Bebidas')], max_length=20, verbose_name='Categoria'),
        ),
    ]
