# Generated by Django 4.2.7 on 2025-10-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('hamburguer', 'Hambúrguer'), ('Lanches', 'Lanches'), ('Bebidas', 'Bebidas')], max_length=20, verbose_name='Categoria'),
        ),
    ]
