# Generated by Django 4.2.25 on 2025-10-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_favorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={},
        ),
    ]
